./simulator.exe ../test/ACStone/000.main.riscv
./simulator.exe ../test/ACStone/011.const.riscv
./simulator.exe ../test/ACStone/012.const.riscv
./simulator.exe ../test/ACStone/013.const.riscv
./simulator.exe ../test/ACStone/014.const.riscv
./simulator.exe ../test/ACStone/015.const.riscv
./simulator.exe ../test/ACStone/016.const.riscv
./simulator.exe ../test/ACStone/017.const.riscv
./simulator.exe ../test/ACStone/018.const.riscv
./simulator.exe ../test/ACStone/021.cast.riscv
./simulator.exe ../test/ACStone/022.cast.riscv
./simulator.exe ../test/ACStone/023.cast.riscv
./simulator.exe ../test/ACStone/024.cast.riscv
./simulator.exe ../test/ACStone/025.cast.riscv
./simulator.exe ../test/ACStone/026.cast.riscv
./simulator.exe ../test/ACStone/027.cast.riscv
./simulator.exe ../test/ACStone/031.add.riscv
./simulator.exe ../test/ACStone/032.add.riscv
./simulator.exe ../test/ACStone/033.add.riscv
./simulator.exe ../test/ACStone/034.add.riscv
./simulator.exe ../test/ACStone/041.sub.riscv
./simulator.exe ../test/ACStone/042.sub.riscv
./simulator.exe ../test/ACStone/043.sub.riscv
./simulator.exe ../test/ACStone/044.sub.riscv
./simulator.exe ../test/ACStone/051.mul.riscv
./simulator.exe ../test/ACStone/052.mul.riscv
./simulator.exe ../test/ACStone/053.mul.riscv
./simulator.exe ../test/ACStone/054.mul.riscv
./simulator.exe ../test/ACStone/055.mul.riscv
./simulator.exe ../test/ACStone/056.mul.riscv
./simulator.exe ../test/ACStone/057.mul.riscv
./simulator.exe ../test/ACStone/058.mul.riscv
./simulator.exe ../test/ACStone/061.div.riscv
./simulator.exe ../test/ACStone/062.div.riscv
./simulator.exe ../test/ACStone/063.div.riscv
./simulator.exe ../test/ACStone/064.div.riscv
./simulator.exe ../test/ACStone/065.div.riscv
./simulator.exe ../test/ACStone/066.div.riscv
./simulator.exe ../test/ACStone/071.bool.riscv
./simulator.exe ../test/ACStone/072.bool.riscv
./simulator.exe ../test/ACStone/073.bool.riscv
./simulator.exe ../test/ACStone/074.bool.riscv
./simulator.exe ../test/ACStone/075.bool.riscv
./simulator.exe ../test/ACStone/076.bool.riscv
./simulator.exe ../test/ACStone/077.bool.riscv
./simulator.exe ../test/ACStone/078.bool.riscv
./simulator.exe ../test/ACStone/081.shift.riscv
./simulator.exe ../test/ACStone/082.shift.riscv
./simulator.exe ../test/ACStone/083.shift.riscv
./simulator.exe ../test/ACStone/084.shift.riscv
./simulator.exe ../test/ACStone/085.shift.riscv
./simulator.exe ../test/ACStone/086.shift.riscv
./simulator.exe ../test/ACStone/111.if.riscv
./simulator.exe ../test/ACStone/112.if.riscv
./simulator.exe ../test/ACStone/113.if.riscv
./simulator.exe ../test/ACStone/114.if.riscv
./simulator.exe ../test/ACStone/115.if.riscv
./simulator.exe ../test/ACStone/116.if.riscv
./simulator.exe ../test/ACStone/117.if.riscv
./simulator.exe ../test/ACStone/118.if.riscv
./simulator.exe ../test/ACStone/119.if.riscv
./simulator.exe ../test/ACStone/121.loop.riscv
./simulator.exe ../test/ACStone/122.loop.riscv
./simulator.exe ../test/ACStone/123.loop.riscv
./simulator.exe ../test/ACStone/124.loop.riscv
./simulator.exe ../test/ACStone/125.loop.riscv
./simulator.exe ../test/ACStone/126.loop.riscv
./simulator.exe ../test/ACStone/131.call.riscv
./simulator.exe ../test/ACStone/132.call.riscv
./simulator.exe ../test/ACStone/133.call.riscv
./simulator.exe ../test/ACStone/134.call.riscv
./simulator.exe ../test/ACStone/141.array.riscv
./simulator.exe ../test/ACStone/142.array.riscv
./simulator.exe ../test/ACStone/143.array.riscv
./simulator.exe ../test/ACStone/144.array.riscv
./simulator.exe ../test/ACStone/145.array.riscv
./simulator.exe ../test/ACStone/146.array.riscv
